before_install:
# package-lock.json was introduced in npm@5
- '[[ $(node -v) =~ ^v9.*$ ]] || npm install -g npm@latest' # skipped when using node 9
- npm install -g greenkeeper-lockfile
install: npm install
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload

jobs:
  include:
    - stage: build
      language: node_js
      node_js:
        - "lts/*"
      script:
        - NODE_ENV=production npm run build
    -
      language: node_js
      node_js:
        - "node"
      script:
        - NODE_ENV=production npm run build
    - stage: lint
      language: node_js
      node_js:
        - "lts/*"
      script:
        - npm run lint
    -
      language: node_js
      node_js:
        - "node"
      script:
        - npm run lint
    - stage: test
      language: node_js
      node_js:
        - "lts/*"
      script:
        - npm run test
        - npm run coverage
    -
      language: node_js
      node_js:
        - "node"
      script:
        - npm run test
        - npm run coverage
    - stage: docs
      language: node_js
      node_js:
        - "node"
      script:
        - npm run doc
        - mkdir .public
        - cp -r doc/generated/@pikselpalette/sequoia-js-client-sdk/*/* .public
      deploy:
        local-dir: './.public'
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
        keep-history: true
        on:
          branch: master
